name: Meson

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo -E apt-get -y install meson libgtk-3-dev libxdo-dev
      
    - name: Setup build
      run: meson build
      
    - name: Compile
      run: cd build && ninja
