name: Meson

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: meson build
      
    - name: Compile with ninja
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: ninja
